/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package midterm;
import java.util.Random;
import javax.swing.JTextArea;
/**
 *
 * @author kevin
 */
public class MidtermGUI extends javax.swing.JFrame {
        Random rv1 = new Random();
        int lotterySelection[] = new int[18]; //Array to hold 18 random numbers
     //Array to hold each ticket number and the bonus number
        int take3tickArr [] = new int[4];  
        int take4tickArr[] = new int[5];
        int take5tickArr[] = new int[6];
        //Ticket prize amounts for each ticket
        int take_3 = 1000;
        int take_4 = 10000;
        int take_5 = 100000;
    /**
     * Creates new form MidtermGUI
     */
    public MidtermGUI() {
      initComponents();
        jTextArea1.setRows(20);
        jTextArea1.setColumns(50);
    }
   
    public static void generateTicket(int[] ticket, int mainCount, int[] lottery, Random rv1) {
     //Filling each slot in the ticket with a random number between 1 and 64
        for(int i = 0; i < mainCount; i++) {
            boolean found = true;
               
            while(found) {
                int num = rv1.nextInt(64) + 1;
                found = false;

                for(int j = 0; j < i; j++) {
                    if (ticket[j] == num) {   
                        found = true;
                        break;
                    }
                }

                if(!found) {
                    ticket[i] = num;   //storing number
                }
            }
        }
      //Generating bonus number from the winning pool thats different from main ticket numbers
        boolean validBonus = false;

        while(!validBonus) {
            int bonus = lottery[rv1.nextInt(lottery.length)];
            validBonus = true;

            for (int i = 0; i < mainCount; i++) {
                if (ticket[i] == bonus) {
                    validBonus = false;
                    break;
                }
            }
            //If the bonus is valid we store it in the last slot of the ticket array
            if (validBonus) {
                ticket[mainCount] = bonus;
            }
        }
    }

    public static void printArray(int[] arr) {
        for (int i = 0; i < arr.length; i++) {
            if(i == arr.length - 1) {
                System.out.print("|Bonus: " + arr[i]);
            } else {
                System.out.print(arr[i] + " ");
            }
        }
        System.out.println("\n");
    }

    public static int checkWin(int[] ticket, int mainCount, int[] lottery, int basePrize) {

        int matches = 0;

        for (int i = 0; i < mainCount; i++) {
            for (int j = 0; j < lottery.length; j++) {
                if(ticket[i] == lottery[j]) {
                    matches++;
                    break;
                }
            }
        }

        int prize = 0;

        if (matches == mainCount) {
            prize = basePrize;
            int bonus = ticket[mainCount];
            boolean hasBonus = false;

            for (int i = 0; i < lottery.length; i++) {
                if(lottery[i] == bonus) {
                    hasBonus = true;
                    break;
                }
            }

            if (hasBonus) {
                prize *= 10;
            }
        }
       return prize;
    }
        
           
       
       private void printToArea(int[] arr) {
         for (int i = 0; i < arr.length; i++) {
           if (i == arr.length - 1) {
           jTextArea1.append("|Bonus: " + arr[i] + "\n");
        } else {
            jTextArea1.append(arr[i] + " ");
        }
    }
}
    
       

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameOutputWindow = new javax.swing.JScrollPane();
        gameOutputArea = new javax.swing.JTextArea();
        start = new javax.swing.JButton();
        check = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gameOutputArea.setEditable(false);
        gameOutputArea.setColumns(20);
        gameOutputArea.setRows(5);
        gameOutputWindow.setViewportView(gameOutputArea);

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        check.setText("Check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameOutputWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameOutputWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        jTextArea1.setText("");

        //Generate Lottery
       for(int i = 0; i < lotterySelection.length; i++) {
           boolean found = true;

          while(found) {
             int num = rv1.nextInt(64) + 1;
             found = false;

           for(int j = 0; j < i; j++) {
                if (lotterySelection[j] == num) {
                found = true;
                 break;
                }       
             }
             if(!found) {
              lotterySelection[i] = num;
             }  
          }
    }//GEN-LAST:event_startActionPerformed
     //Generating Tickets
     generateTicket(take3tickArr,3,lotterySelection, rv1);
     generateTicket(take4tickArr,4, lotterySelection, rv1);
     generateTicket(take5tickArr,5,lotterySelection, rv1);
             
     //Displayin Screen to UI
     jTextArea1.append("Winning Picks: \n");
     printToArea(lotterySelection);

     jTextArea1.append("\nTake 3: \n");
     printToArea(take3tickArr);

     jTextArea1.append("\nTake 4: \n");
     printToArea(take4tickArr);

     jTextArea1.append("\nTake 5: \n");
     printToArea(take5tickArr);

    }

  
   




    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
     jTextArea1.append("\nRESULTS: \n");

     int prize3 = checkWin(take3tickArr, 3, lotterySelection, take_3);
     int prize4 = checkWin(take4tickArr, 4, lotterySelection, take_4);
     int prize5 = checkWin(take5tickArr, 5, lotterySelection, take_5);

     jTextArea1.append("Take 3: " + (prize3 > 0 ? "WIN! $" + prize3 : "LOST") + "\n");
     jTextArea1.append("Take 4: " + (prize4 > 0 ? "WIN! $" + prize4 : "LOST") + "\n");
     jTextArea1.append("Take 5: " + (prize5 > 0 ? "WIN! $" + prize5 : "LOST") + "\n");
    }//GEN-LAST:event_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MidtermGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MidtermGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MidtermGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MidtermGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MidtermGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check;
    private javax.swing.JTextArea gameOutputArea;
    private javax.swing.JScrollPane gameOutputWindow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
 }
